DROP DATABASE NINEBBSDB;
CREATE DATABASE NINEBBSDB;
USE NINEBBSDB;
/******************************************************************
*org.mariadb.jdbc.Driver
*jdbc:mysql://localhost:3306, user, password
*<dependency>
*    <groupId>org.mariadb.jdbc</groupId>
*    <artifactId>mariadb-java-client</artifactId>
*    <version>1.1.7</version>
*</dependency>
******************************************************************/
/******************************************************************
*Tables
******************************************************************/
/*user type*/
CREATE TABLE NINEBBSDB.KB_USER_TYPE (
	USER_TYPE_ID INT NOT NULL AUTO_INCREMENT,
	USER_ACCOUNT varchar(25) NOT NULL,
	CONSTRAINT KB_USER_TYPE_PK PRIMARY KEY (USER_TYPE_ID)
)
ENGINE=InnoDB
DEFAULT CHARSET=utf8
COLLATE=utf8_general_ci;

/*categorizing boards by specific keywords*/
CREATE TABLE NINEBBSDB.KB_CATEGORY (
	CATEGORY_ID INT NOT NULL AUTO_INCREMENT,
	CATEGORY_NAME varchar(30) NOT NULL
)
ENGINE=InnoDB
DEFAULT CHARSET=utf8
COLLATE=utf8_general_ci;

/*have a list of banned ip addresses, date submitted, and date to expire*/
CREATE TABLE NINEBBSDB.KB_BANNED_IP (
	BANNED_ID INT NOT NULL AUTO_INCREMENT,
	BANNED_IP_ADDR varchar(16) NOT NULL,
	BANNED_DATE TIMESTAMP NOT NULL,
	BANNED_EXP_DATE TIMESTAMP NULL,
	CONSTRAINT KB_BANNED_IP_PK PRIMARY KEY (BANNED_ID)
)
ENGINE=InnoDB
DEFAULT CHARSET=utf8
COLLATE=utf8_general_ci;

/*board list with maximum thread and post limits to enforce bumping and displaying board info*/
CREATE TABLE NINEBBSDB.KB_BOARDS (
	BOARD_ID INT NOT NULL AUTO_INCREMENT,
	BOARD_NAME varchar(35) NOT NULL,
	BOARD_DESC varchar(255) NOT NULL,
	BOARD_START_DATE TIMESTAMP NOT NULL,
	MAX_THREADS INT NOT NULL,
	MAX_POSTS INT NOT NULL,
	CATEGORY_ID INT NULL,
	CONSTRAINT KB_BOARDS_PK PRIMARY KEY (BOARD_ID),
	CONSTRAINT KB_BOARDS_KB_CATEGORY_FK FOREIGN KEY (CATEGORY_ID) REFERENCES NINEBBSDB.KB_CATEGORY(CATEGORY_ID);
)
DEFAULT CHARSET=utf8
COLLATE=utf8_general_ci;

/*Threads hold postable discussions, includes the ability to define the subject, and a starting date*/
CREATE TABLE NINEBBSDB.KB_THREADS (
	THREAD_ID INT NOT NULL AUTO_INCREMENT,
	THREAD_TITLE varchar(35) NOT NULL,
	THREAD_SUBJECT varchar(35) DEFAULT NULL NULL,
	THREAD_CONTENT TEXT NOT NULL,
	THREAD_START_DATE TIMESTAMP NOT NULL,
	THREAD_MODIFIED_DATE TIMESTAMP DEFAULT NULL NULL,
	THREAD_FLAG INT DEFAULT NULL NULL,
	THREAD_IP_ADDRESS varchar(16) NOT NULL,
	AUTH_USER_ID INT NULL,
	BOARD_ID INT NOT NULL,
	CONSTRAINT KB_THREADS_PK PRIMARY KEY (THREAD_ID),
	CONSTRAINT KB_THREADS_KB_BOARDS_FK FOREIGN KEY (BOARD_ID) REFERENCES NINEBBSDB.KB_BOARDS(BOARD_ID),
	CONSTRAINT KB_THREADS_KB_AUTH_USER_LIST_FK FOREIGN KEY (AUTH_USER_ID) REFERENCES NINEBBSDB.KB_AUTH_USER_LIST(AUTH_USER_ID)
)
ENGINE=InnoDB
DEFAULT CHARSET=utf8
COLLATE=utf8_general_ci;

/*Posts are attached to specific threads, allowing for a reply chain and an easy layout*/
CREATE TABLE NINEBBSDB.KB_POSTS (
	POST_ID INT NOT NULL AUTO_INCREMENT,
	POST_NAME varchar(55) DEFAULT 'Anonymous' NOT NULL,
	POST_CONTENT TEXT NOT NULL,
	POST_START_DATE TIMESTAMP NOT NULL,
	POST_MODIFIED_DATE TIMESTAMP NULL,
	POST_FLAG INT NULL,
	POST_IP_ADDRESS varchar(16) NOT NULL,
	AUTH_USER_ID INT NULL,
	THREAD_ID INT NOT NULL,
	CONSTRAINT KB_POSTS_PK PRIMARY KEY (POST_ID),
	CONSTRAINT KB_POSTS_KB_THREADS_FK FOREIGN KEY (THREAD_ID) REFERENCES NINEBBSDB.KB_THREADS(THREAD_ID),
	CONSTRAINT KB_POSTS_KB_AUTH_USER_LIST_FK FOREIGN KEY (AUTH_USER_ID) REFERENCES NINEBBSDB.KB_AUTH_USER_LIST(AUTH_USER_ID)
)
DEFAULT CHARSET=utf8
COLLATE=utf8_general_ci;

/*if a user inputs a name and password in the post_name field, check this table to find special users, moderators, or admins*/
CREATE TABLE NINEBBSDB.KB_AUTH_USER_LIST (
	AUTH_USER_ID INT NOT NULL AUTO_INCREMENT,
	USER_NAME varchar(50) NOT NULL,
	USER_TYPE_ID INT NULL,
	CONSTRAINT KB_AUTH_USER_LIST_PK PRIMARY KEY (AUTH_USER_ID),
	CONSTRAINT KB_AUTH_USER_LIST_KB_USER_TYPE_FK FOREIGN KEY (USER_TYPE_ID) REFERENCES NINEBBSDB.KB_USER_TYPE(USER_TYPE_ID)
)
ENGINE=InnoDB
DEFAULT CHARSET=utf8
COLLATE=utf8_general_ci;

/*A report table that refers to a thread or post that users may deem offensive. contains date posted and a count*/
CREATE TABLE NINEBBSDB.KB_REPORTS (
	REPORT_ID INT NOT NULL AUTO_INCREMENT,
	REPORT_IP varchar(16) NOT NULL,
	REPORT_DATE TIMESTAMP NOT NULL,
	REPORT_COUNT INT NULL,
	THREAD_ID INT DEFAULT NULL NULL,
	POST_ID INT DEFAULT NULL NULL,
	CONSTRAINT KB_REPORTS_PK PRIMARY KEY (REPORT_ID),
	CONSTRAINT KB_REPORTS_KB_THREADS_FK FOREIGN KEY (THREAD_ID) REFERENCES NINEBBSDB.KB_THREADS(THREAD_ID),
	CONSTRAINT KB_REPORTS_KB_POSTS_FK FOREIGN KEY (POST_ID) REFERENCES NINEBBSDB.KB_POSTS(POST_ID)
)
ENGINE=InnoDB
DEFAULT CHARSET=utf8
COLLATE=utf8_general_ci;

/*add database constraints*/
ALTER TABLE NINEBBSDB.KB_POSTS ADD CONSTRAINT KB_POSTS_KB_USER_TYPE_FK 
FOREIGN KEY (USER_TYPE_ID) REFERENCES NINEBBSDB.KB_THREADS(THREAD_ID);

ALTER TABLE NINEBBSDB.KB_THREADS ADD CONSTRAINT KB_THREADS_KB_BOARDS_FK 
FOREIGN KEY (BOARD_ID) REFERENCES NINEBBSDB.KB_BOARDS(BOARD_ID);

INSERT INTO KB_USER(USER_TYPE_ID, USER_ACCOUNT) VALUES(1,'NORMAL_USER');
INSERT INTO KB_USER(USER_TYPE_ID, USER_ACCOUNT) VALUES(2,'PREMIUM_USER');
INSERT INTO KB_USER(USER_TYPE_ID, USER_ACCOUNT) VALUES(3,'MODERATOR');
INSERT INTO KB_USER(USER_TYPE_ID, USER_ACCOUNT) VALUES(4,'ADMINISTRATOR');

INSERT INTO KB_CATEGORY(CATEGORY_ID, CATEGORY_NAME) VALUES(1,'MATH');
INSERT INTO KB_CATEGORY(CATEGORY_ID, CATEGORY_NAME) VALUES(2,'SCIENCE');
INSERT INTO KB_CATEGORY(CATEGORY_ID, CATEGORY_NAME) VALUES(3,'TECHNOLOGY');
INSERT INTO KB_CATEGORY(CATEGORY_ID, CATEGORY_NAME) VALUES(4,'ART');
INSERT INTO KB_CATEGORY(CATEGORY_ID, CATEGORY_NAME) VALUES(5,'ENTERTAINMENT');
INSERT INTO KB_CATEGORY(CATEGORY_ID, CATEGORY_NAME) VALUES(6,'HISTORY');

/****************************************************************************
create users for the specific database tables
****************************************************************************/
DROP USER 'anonymous'@'localhost';
CREATE USER 'anonymous'@'localhost' IDENTIFIED BY 'pa$$00rRd';
GRANT SELECT,INSERT
ON NINEBBSDB.KB_THREADS, NINEBBSDB.KB_POSTS
TO 'anonymous'@'localhost';
GRANT SELECT/*for board access*/
ON NINEBBSDB.KB_BOARDS
TO 'anonymous'@'localhost';

DROP USER 'moderator'@'localhost';
CREATE USER 'moderator'@'localhost' IDENTIFIED BY 'P4$WWW00RRdd';
GRANT SELECT,INSERT,UPDATE,DELETE
ON NINEBBSDB.KB_THREADS, NINEBBSDB.KB_POSTS
TO 'moderator'@'localhost';
GRANT SELECT
ON NINEBBSDB.KB_BOARDS
TO 'moderator'@'localhost';

DROP USER 'administrator'@'localhost';
CREATE USER 'administrator'@'localhost' IDENTIFIED BY 'T3P4$W$W#W00#rRfd';
GRANT SELECT,INSERT,UPDATE,DELETE,CREATE,DROP
ON NINEBBSDB.*/*admin gets full access*/
TO 'administrator'@'localhost';